package com.neu.edu.hw5p4.pojo;
// Generated Feb 28, 2016 2:26:30 PM by Hibernate Tools 4.3.1



/**
 * Salesorder generated by hbm2java
 */
public class SalesOrder  implements java.io.Serializable {


     private String salesorderid;
     private String accountnumber;
     private String billtoaddressid;
     private String comment;
     private String creditcardapprovalcode;
     private String creditcardid;
     private String currencyrateid;
     private String customerid;
     private String duedate;
     private String freight;
     private String modifieddate;
     private String onlineorderflag;
     private String orderdate;
     private String purchaseordernumber;
     private String revisionnumber;
     private String salesordernumber;
     private String salespersonid;
     private String shipdate;
     private String shipmethodid;
     private String shiptoaddressid;
     private String status;
     private String subtotal;
     private String taxamt;
     private String territoryid;
     private String totaldue;

    public SalesOrder() {
    }

	
    public SalesOrder(String salesorderid) {
        this.salesorderid = salesorderid;
    }
    public SalesOrder(String salesorderid, String accountnumber, String billtoaddressid, String comment, String creditcardapprovalcode, String creditcardid, String currencyrateid, String customerid, String duedate, String freight, String modifieddate, String onlineorderflag, String orderdate, String purchaseordernumber, String revisionnumber, String salesordernumber, String salespersonid, String shipdate, String shipmethodid, String shiptoaddressid, String status, String subtotal, String taxamt, String territoryid, String totaldue) {
       this.salesorderid = salesorderid;
       this.accountnumber = accountnumber;
       this.billtoaddressid = billtoaddressid;
       this.comment = comment;
       this.creditcardapprovalcode = creditcardapprovalcode;
       this.creditcardid = creditcardid;
       this.currencyrateid = currencyrateid;
       this.customerid = customerid;
       this.duedate = duedate;
       this.freight = freight;
       this.modifieddate = modifieddate;
       this.onlineorderflag = onlineorderflag;
       this.orderdate = orderdate;
       this.purchaseordernumber = purchaseordernumber;
       this.revisionnumber = revisionnumber;
       this.salesordernumber = salesordernumber;
       this.salespersonid = salespersonid;
       this.shipdate = shipdate;
       this.shipmethodid = shipmethodid;
       this.shiptoaddressid = shiptoaddressid;
       this.status = status;
       this.subtotal = subtotal;
       this.taxamt = taxamt;
       this.territoryid = territoryid;
       this.totaldue = totaldue;
    }
   
    public String getSalesorderid() {
        return this.salesorderid;
    }
    
    public void setSalesorderid(String salesorderid) {
        this.salesorderid = salesorderid;
    }
    public String getAccountnumber() {
        return this.accountnumber;
    }
    
    public void setAccountnumber(String accountnumber) {
        this.accountnumber = accountnumber;
    }
    public String getBilltoaddressid() {
        return this.billtoaddressid;
    }
    
    public void setBilltoaddressid(String billtoaddressid) {
        this.billtoaddressid = billtoaddressid;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getCreditcardapprovalcode() {
        return this.creditcardapprovalcode;
    }
    
    public void setCreditcardapprovalcode(String creditcardapprovalcode) {
        this.creditcardapprovalcode = creditcardapprovalcode;
    }
    public String getCreditcardid() {
        return this.creditcardid;
    }
    
    public void setCreditcardid(String creditcardid) {
        this.creditcardid = creditcardid;
    }
    public String getCurrencyrateid() {
        return this.currencyrateid;
    }
    
    public void setCurrencyrateid(String currencyrateid) {
        this.currencyrateid = currencyrateid;
    }
    public String getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }
    public String getDuedate() {
        return this.duedate;
    }
    
    public void setDuedate(String duedate) {
        this.duedate = duedate;
    }
    public String getFreight() {
        return this.freight;
    }
    
    public void setFreight(String freight) {
        this.freight = freight;
    }
    public String getModifieddate() {
        return this.modifieddate;
    }
    
    public void setModifieddate(String modifieddate) {
        this.modifieddate = modifieddate;
    }
    public String getOnlineorderflag() {
        return this.onlineorderflag;
    }
    
    public void setOnlineorderflag(String onlineorderflag) {
        this.onlineorderflag = onlineorderflag;
    }
    public String getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(String orderdate) {
        this.orderdate = orderdate;
    }
    public String getPurchaseordernumber() {
        return this.purchaseordernumber;
    }
    
    public void setPurchaseordernumber(String purchaseordernumber) {
        this.purchaseordernumber = purchaseordernumber;
    }
    public String getRevisionnumber() {
        return this.revisionnumber;
    }
    
    public void setRevisionnumber(String revisionnumber) {
        this.revisionnumber = revisionnumber;
    }
    public String getSalesordernumber() {
        return this.salesordernumber;
    }
    
    public void setSalesordernumber(String salesordernumber) {
        this.salesordernumber = salesordernumber;
    }
    public String getSalespersonid() {
        return this.salespersonid;
    }
    
    public void setSalespersonid(String salespersonid) {
        this.salespersonid = salespersonid;
    }
    public String getShipdate() {
        return this.shipdate;
    }
    
    public void setShipdate(String shipdate) {
        this.shipdate = shipdate;
    }
    public String getShipmethodid() {
        return this.shipmethodid;
    }
    
    public void setShipmethodid(String shipmethodid) {
        this.shipmethodid = shipmethodid;
    }
    public String getShiptoaddressid() {
        return this.shiptoaddressid;
    }
    
    public void setShiptoaddressid(String shiptoaddressid) {
        this.shiptoaddressid = shiptoaddressid;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(String subtotal) {
        this.subtotal = subtotal;
    }
    public String getTaxamt() {
        return this.taxamt;
    }
    
    public void setTaxamt(String taxamt) {
        this.taxamt = taxamt;
    }
    public String getTerritoryid() {
        return this.territoryid;
    }
    
    public void setTerritoryid(String territoryid) {
        this.territoryid = territoryid;
    }
    public String getTotaldue() {
        return this.totaldue;
    }
    
    public void setTotaldue(String totaldue) {
        this.totaldue = totaldue;
    }




}


