package com.pagalila.pojo;
// Generated Mar 30, 2016 8:01:48 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Adverttable generated by hbm2java
 */
@Entity
@Table(name = "adverttable", catalog = "lab8")
public class Adverttable implements java.io.Serializable {

	private Long id;
	private Usertable usertable;
	private Categorytable categorytable;
	private String message;
	private String title;

	public Adverttable() {
	}

	public Adverttable(Usertable usertable, String message, String title) {
		this.usertable = usertable;
		this.message = message;
		this.title = title;
	}

	public Adverttable(Usertable usertable, Categorytable categorytable, String message, String title) {
		this.usertable = usertable;
		this.categorytable = categorytable;
		this.message = message;
		this.title = title;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user", nullable = false)
	public Usertable getUsertable() {
		return this.usertable;
	}

	public void setUsertable(Usertable usertable) {
		this.usertable = usertable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category")
	public Categorytable getCategorytable() {
		return this.categorytable;
	}

	public void setCategorytable(Categorytable categorytable) {
		this.categorytable = categorytable;
	}

	@Column(name = "message", nullable = false)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
